import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { getSiteSettings, SiteSettings } from './api';
import { useAuth } from './auth';

type Locale = 'zh-CN' | 'en-US';
type TranslationKey = keyof typeof translations['zh-CN'];

type SiteContextValue = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: TranslationKey, vars?: Record<string, string | number>) => string;
  siteSettings: SiteSettings | null;
  refreshSiteSettings: () => Promise<void>;
  announcementOpen: boolean;
  openAnnouncement: () => void;
  closeAnnouncement: () => void;
};

const LOCALE_STORAGE_KEY = 'cybergen_locale';
const ANNOUNCEMENT_SEEN_KEY = 'cybergen_announcement_seen_at';

const translations = {
  'zh-CN': {
    top_history: '历史记录',
    top_register: '注册',
    top_owner: '当前身份',
    top_credits: '余额',
    top_ledger: '账单',
    top_logout: '退出登录',
    top_login: '登录',
    top_announcement: '公告',
    top_tasks: '任务',
    top_recharge: '充值',
    mobile_menu_open: '打开菜单',
    mobile_menu_close: '关闭菜单',
    side_title: '神经链接',
    side_history: '生成历史',
    side_account: '账户概览',
    side_config: '系统设置',
    side_case_admin: '案例管理',
    side_billing: '账单明细',
    side_generate: '开始生成',
    home_scan: '系统扫描',
    home_title: '公开案例',
    home_owner: '当前身份 {value}',
    home_guest: '游客 {value}',
    home_clone_prompt: '复用提示词',
    home_mode: '模式',
    home_mode_edit: '改图',
    home_mode_generate: '生图',
    home_message_edit_sent: '改图请求已发送',
    home_message_generate_sent: '生图请求已发送',
    home_message_queued: '任务已提交，正在排队',
    home_message_processing: '任务执行中，请稍候',
    home_message_saved: '结果已存入历史',
    home_message_waiting: '等待输入',
    home_message_loaded: '已载入配置',
    home_key_group: '分组',
    home_key_group_placeholder: '选择分组',
    home_key_group_loading: '加载分组',
    home_key_group_empty: '你的账号还没有可用分组，请先前往即刻创建分组。',
    home_key_group_create: '创建分组',
    home_key_group_required: '请先选择一个 API Key 分组。',
    home_key_group_selected: '已选择分组：{value}',
    home_placeholder: '在这里输入你的生成提示词...',
    home_ref_image: '参考图',
    home_execute: '执行',
    home_edit: '改图',
    home_generate: '生成',
    home_size: '清晰度',
    home_aspect_ratio: '比例',
    home_quality: '质量',
    home_batch_count: '数量',
    home_batch_option: '{value} 张',
    home_batch_submitting: '正在提交第 {current}/{total} 张',
    home_batch_queued: '已提交 {value} 个任务',
    home_loading_feed: '案例加载中...',
	    home_loading_more: '正在加载更多案例...',
	    home_load_more: '加载更多案例',
	    home_all_loaded: '案例已全部加载',
	    home_empty_feed: '暂时还没有可展示的案例。',
	    home_sort_label: '排序',
	    home_sort_latest: '发布时间',
	    home_sort_likes: '点赞数',
	    home_sort_comments: '评论数',
	    case_public_gallery: '公开案例',
	    case_login_required: '请先登录后再操作。',
	    case_comments: '评论',
	    case_comments_loading: '评论加载中',
	    case_comments_empty: '暂无评论',
	    case_comment_placeholder: '写下你的评论...',
	    case_comment_submit: '发表评论',
	    case_title: '案例标题',
	    case_author: '作者',
	    case_image_url: '图片地址',
	    case_image_path: '本地图片路径',
	    case_prompt: '提示词',
	    case_status: '状态',
	    case_status_visible: '显示',
	    case_status_hidden: '隐藏',
	    case_status_deleted: '删除',
	    case_admin_title: '案例管理',
	    case_admin_tag: '后台管理',
	    case_admin_subtitle: '按发布时间管理全部公开案例，搜索提示词，查看评论并调整点赞数。',
	    case_admin_cases_tab: '案例',
	    case_admin_new: '新建',
	    case_admin_create: '新增案例',
	    case_admin_update: '保存案例',
	    case_admin_edit: '编辑',
	    case_admin_cancel_edit: '取消编辑',
	    case_admin_refresh: '刷新案例',
	    case_admin_saved: '案例已保存',
	    case_admin_empty: '暂无案例。',
	    case_admin_required: '请填写案例标题、提示词，并至少提供图片地址或本地图片路径。',
	    case_admin_comments: '评论',
	    case_admin_add_comment: '新增后台评论',
	    case_admin_comment_edit: '修改评论内容',
	    case_admin_select_case: '选择案例',
	    case_admin_comment_required: '请选择案例并填写评论内容。',
	    case_admin_search_prompt: '搜索提示词...',
	    case_admin_search_submit: '搜索',
	    case_admin_stats: '互动',
	    case_admin_created_at: '发布时间',
	    case_admin_loading: '案例加载中',
	    case_admin_page_status: '第 {page} / {pages} 页，共 {total} 条',
	    case_admin_prev: '上一页',
	    case_admin_next: '下一页',
	    case_admin_admin_only: '仅管理员可访问案例管理。',
	    case_admin_no_image: '无图',
	    case_admin_detail: '案例详情',
	    case_admin_like_count: '点赞数',
	    case_admin_like_invalid: '点赞数必须是大于等于 0 的整数。',
	    case_admin_save_likes: '保存',
	    case_admin_delete_comment: '删除评论',
	    case_comment_body: '评论内容',
    history_tag: '神经数据库',
    history_title: '历史档案',
    history_subtitle: '查看并管理此前生成的图像记录。',
    history_retention_notice: '普通图片默认保留 {days} 天，公开案例会长期保留。',
    history_search: '搜索提示词...',
    history_failed: '生成失败',
    history_download: '下载',
    history_delete: '删除',
    history_delete_confirm_title: '确认删除历史记录',
    history_delete_confirm_body: '删除后会移除这条历史记录，并清理对应的本地图片文件；复用同一文件的公开案例也会被删除。此操作不可撤销。',
    history_delete_confirm_cancel: '取消',
    history_delete_confirm_action: '确认删除',
    history_preview: '预览',
    history_regenerate: '重新生成',
    history_publish_case: '公开到案例',
    history_unpublish_case: '取消公开',
    history_published: '已公开',
    history_load_more: '加载更多',
    account_tag: '个人系统',
    account_title: '账户',
    account_identity: '身份信息',
    account_owner: '身份',
    account_registered: '注册用户',
    account_guest: '游客会话',
    account_user: '显示名称',
    account_sub2api_username: '即刻 用户名',
    account_email: '邮箱',
    account_model: '模型',
    account_api_key: '密钥来源',
    account_api_managed: '自动绑定到 即刻 用户',
    account_api_override: '手动覆盖密钥',
    account_api_manual: '游客手动密钥',
    account_api_missing: '未配置',
    account_balance: '余额',
    account_history: '历史数',
    account_succeeded: '{value} 次成功',
    account_edits: '改图数',
    account_last: '最近：{value}',
    billing_tag: '账单',
    billing_title: '余额明细',
    billing_remaining: '即刻 剩余额度',
    billing_synced: '已从 即刻 /v1/usage 同步',
    billing_not_configured: '未配置 即刻 API Key',
    billing_local_ledger: '本地账单',
    billing_empty: '暂无账单数据',
    billing_recharge: '前往充值',
    billing_recharge_desc: '充值与购买额度请前往 即刻 站点。',
    billing_actual: '实际扣费',
    billing_estimated: '估算，仅供参考',
    config_profile: '用户资料',
    config_mode: '模式',
    config_mode_user: '即刻 用户',
    config_mode_guest: '游客',
    config_balance: '余额：{value}',
    config_guest_tip: '游客模式使用手动填写的 即刻 API Key。注册或登录后，会自动绑定你的个人 Key。',
    config_sign_in: '登录',
    config_register: '注册',
    config_title: '运行配置',
    config_session_user: '账号会话',
    config_session_guest: '游客会话',
    config_user_desc: '当前配置绑定到已登录的 即刻 用户。系统会自动选择个人 Key，必要时你也可以改为共享福利 Key。',
    config_guest_desc: '游客模式按浏览器 Cookie 隔离数据，使用手动保存的 即刻 API Key，后端会自动转发到内部生图服务。',
	    config_cases: '案例库',
	    config_cases_summary: '公开 {total} 条案例 · 最近 {time}',
	    config_cases_engagement: '{likes} 个点赞 · {comments} 条评论',
    config_user_name: '用户名',
    config_model: '模型',
    config_size: '尺寸',
    config_quality: '质量',
    config_api_key: '即刻 密钥',
    config_saved_key: '已保存密钥：{value}',
    config_key_managed: '自动绑定',
    config_key_override: '手动覆盖',
    config_key_manual: '手动',
    config_restore_key: '恢复自动绑定密钥',
    config_test: '测试连接',
    config_save: '保存配置',
    config_ledger: '消费矩阵',
    config_ledger_empty: '暂无本地账单',
    config_view_ledger: '查看完整账单',
    config_status_saved: '配置已保存',
    config_status_connected: '连接正常：{value}',
    config_status_restored: '已恢复自动绑定密钥',
    config_status_site_saved: '站点设置已保存',
    config_site_title: '界面与公告',
    config_site_desc: '语言选择会保存在当前浏览器。管理员保存后，会更新站点默认语言与公告内容。',
    login_access: '访问入口',
    login_title: '登录',
    login_title_2fa: '二次验证',
    login_desc: '使用你的 即刻 账户登录。本站会维护自己的会话，并自动绑定你的个人 API Key。',
    login_desc_2fa: '请输入 {value} 的 6 位验证码。',
    login_email: '邮箱',
    login_password: '密码',
    login_totp: 'TOTP 验证码',
    login_submit: '登录',
    login_submit_2fa: '验证 2FA',
    login_new: '还没有账号？',
    register_access: '注册入口',
    register_title: '创建账户',
    register_desc: '注册入口在本站，但账号实际创建在你部署的 即刻 中。',
    register_disabled: '当前连接的 即刻 已关闭注册。',
    register_email: '邮箱',
    register_password: '密码',
    register_verify_code: '验证码',
    register_send_code: '发送验证码',
    register_promo: '优惠码',
    register_invitation: '邀请码',
    register_submit: '注册',
    register_exists: '已经注册？',
    lang_label: '界面语言',
    lang_zh: '中文',
    lang_en: 'English',
    site_announcement: '站点公告',
    site_announcement_enabled: '启用公告弹窗',
    site_announcement_title: '公告标题',
    site_announcement_body: '公告内容',
    site_upstream: '上游服务',
    site_upstream_hint: '留空则使用环境变量。修改后全站生图、注册登录、余额和用量明细都会走新的上游。',
    site_provider_base_url: 'OpenAI 兼容接口地址',
    site_auth_base_url: '认证管理接口地址',
	    site_upstream_effective: '当前生效：{value}',
    site_announcement_save: '保存公告',
    site_settings_save: '保存站点设置',
    site_admin_only: '仅管理员可编辑站点设置。',
    announcement_empty: '当前没有公告内容。',
    modal_close: '关闭',
    modal_preview: '图片预览',
    modal_open_image: '打开原图',
    tasks_title: '任务中心',
    tasks_subtitle: '提交后的生图和改图任务会在这里继续执行。',
    tasks_empty: '当前还没有任务。',
    tasks_open_history: '查看历史',
    tasks_active: '{value} 个运行中',
    tasks_idle: '空闲',
    tasks_filter_all: '全部',
    tasks_filter_active: '运行中',
    tasks_filter_succeeded: '已完成',
    tasks_filter_failed: '失败',
    tasks_status_queued: '排队中',
    tasks_status_running: '执行中',
    tasks_status_succeeded: '已完成',
    tasks_status_failed: '失败',
    tasks_toast_succeeded: '任务完成',
    tasks_toast_failed: '任务失败',
  },
  'en-US': {
    top_history: 'History',
    top_register: 'Register',
    top_owner: 'Owner',
    top_credits: 'Credits',
    top_ledger: 'Ledger',
    top_logout: 'Logout',
    top_login: 'Login',
    top_announcement: 'Announcement',
    top_tasks: 'Tasks',
    top_recharge: 'Recharge',
    mobile_menu_open: 'Open menu',
    mobile_menu_close: 'Close menu',
    side_title: 'Neural Link',
    side_history: 'Generation History',
    side_account: 'Account Overview',
    side_config: 'System Settings',
    side_case_admin: 'Case Manager',
    side_billing: 'Billing',
    side_generate: 'Generate New',
    home_scan: 'System Scan',
    home_title: 'Public Cases',
    home_owner: 'Owner {value}',
    home_guest: 'Guest {value}',
    home_clone_prompt: 'Clone Prompt',
    home_mode: 'Mode',
    home_mode_edit: 'Edit',
    home_mode_generate: 'Generate',
    home_message_edit_sent: 'Edit request dispatched',
    home_message_generate_sent: 'Generation request dispatched',
    home_message_queued: 'Task submitted and queued',
    home_message_processing: 'Task running, please wait',
    home_message_saved: 'Result stored in archive',
    home_message_waiting: 'Awaiting input',
    home_message_loaded: 'Selected configuration loaded',
    home_key_group: 'Group',
    home_key_group_placeholder: 'Select group',
    home_key_group_loading: 'Loading groups',
    home_key_group_empty: 'No available groups on your account. Create one on 即刻 first.',
    home_key_group_create: 'Create Group',
    home_key_group_required: 'Select an API key group first.',
    home_key_group_selected: 'Selected group: {value}',
    home_placeholder: 'Enter your prompt here...',
    home_ref_image: 'Ref Image',
    home_execute: 'Execute',
    home_edit: 'Edit',
    home_generate: 'Generate',
    home_size: 'Size',
    home_aspect_ratio: 'Ratio',
    home_quality: 'Quality',
    home_batch_count: 'Count',
    home_batch_option: '{value} image(s)',
    home_batch_submitting: 'Submitting {current}/{total}',
    home_batch_queued: '{value} tasks submitted',
    home_loading_feed: 'Loading prompt cases...',
	    home_loading_more: 'Loading more cases...',
	    home_load_more: 'Load More Cases',
	    home_all_loaded: 'All cases loaded',
	    home_empty_feed: 'No cases available yet.',
	    home_sort_label: 'Sort',
	    home_sort_latest: 'Published',
	    home_sort_likes: 'Likes',
	    home_sort_comments: 'Comments',
	    case_public_gallery: 'Public Case',
	    case_login_required: 'Sign in before taking this action.',
	    case_comments: 'Comments',
	    case_comments_loading: 'Loading comments',
	    case_comments_empty: 'No comments yet',
	    case_comment_placeholder: 'Write a comment...',
	    case_comment_submit: 'Post Comment',
	    case_title: 'Case Title',
	    case_author: 'Author',
	    case_image_url: 'Image URL',
	    case_image_path: 'Local Image Path',
	    case_prompt: 'Prompt',
	    case_status: 'Status',
	    case_status_visible: 'Visible',
	    case_status_hidden: 'Hidden',
	    case_status_deleted: 'Deleted',
	    case_admin_title: 'Case Manager',
	    case_admin_tag: 'Admin Console',
	    case_admin_subtitle: 'Manage all public cases by publish time, search prompts, review comments, and adjust likes.',
	    case_admin_cases_tab: 'Cases',
	    case_admin_new: 'New',
	    case_admin_create: 'Create Case',
	    case_admin_update: 'Save Case',
	    case_admin_edit: 'Edit',
	    case_admin_cancel_edit: 'Cancel Edit',
	    case_admin_refresh: 'Refresh Cases',
	    case_admin_saved: 'Case saved',
	    case_admin_empty: 'No cases yet.',
	    case_admin_required: 'Fill in the title, prompt, and at least one image URL or local image path.',
	    case_admin_comments: 'Comments',
	    case_admin_add_comment: 'Add admin comment',
	    case_admin_comment_edit: 'Edit comment body',
	    case_admin_select_case: 'Select case',
	    case_admin_comment_required: 'Select a case and enter comment content.',
	    case_admin_search_prompt: 'Search prompts...',
	    case_admin_search_submit: 'Search',
	    case_admin_stats: 'Engagement',
	    case_admin_created_at: 'Published',
	    case_admin_loading: 'Loading cases',
	    case_admin_page_status: 'Page {page} / {pages}, {total} total',
	    case_admin_prev: 'Previous page',
	    case_admin_next: 'Next page',
	    case_admin_admin_only: 'Only admins can access case management.',
	    case_admin_no_image: 'No image',
	    case_admin_detail: 'Case Detail',
	    case_admin_like_count: 'Likes',
	    case_admin_like_invalid: 'Likes must be an integer greater than or equal to 0.',
	    case_admin_save_likes: 'Save',
	    case_admin_delete_comment: 'Delete comment',
	    case_comment_body: 'Comment body',
    history_tag: 'Neural Database',
    history_title: 'Archive',
    history_subtitle: 'Access and manage previously synthesized visual records.',
    history_retention_notice: 'Regular images are kept for {days} days by default. Public cases are retained long term.',
    history_search: 'Search prompts...',
    history_failed: 'Generation failed',
    history_download: 'Download',
    history_delete: 'Delete',
    history_delete_confirm_title: 'Confirm Delete',
    history_delete_confirm_body: 'This removes the history item and cleans up its local image file. Public cases reusing the same file are also deleted. This cannot be undone.',
    history_delete_confirm_cancel: 'Cancel',
    history_delete_confirm_action: 'Delete',
    history_preview: 'Preview',
    history_regenerate: 'Re-Generate',
    history_publish_case: 'Publish Case',
    history_unpublish_case: 'Unpublish',
    history_published: 'Published',
    history_load_more: 'Load More',
    account_tag: 'Personal System',
    account_title: 'Account',
    account_identity: 'Identity',
    account_owner: 'Owner',
    account_registered: 'Registered User',
    account_guest: 'Guest Session',
    account_user: 'Display Name',
    account_sub2api_username: '即刻 Username',
    account_email: 'Email',
    account_model: 'Model',
    account_api_key: 'API Key',
    account_api_managed: 'Bound to 即刻 user',
    account_api_override: 'Manual override key',
    account_api_manual: 'Manual guest key',
    account_api_missing: 'Missing',
    account_balance: 'Balance',
    account_history: 'History',
    account_succeeded: '{value} succeeded',
    account_edits: 'Edits',
    account_last: 'Last: {value}',
    billing_tag: 'Billing',
    billing_title: 'Balance',
    billing_remaining: '即刻 Remaining',
    billing_synced: 'Synced from 即刻 /v1/usage',
    billing_not_configured: '即刻 API key not configured',
    billing_local_ledger: 'Local Ledger',
    billing_empty: 'No ledger data',
    billing_recharge: 'Recharge',
    billing_recharge_desc: 'Open the 即刻 site to recharge and buy credits.',
    billing_actual: 'Actual cost',
    billing_estimated: 'Estimated, reference only',
    config_profile: 'Owner Profile',
    config_mode: 'Mode',
    config_mode_user: '即刻 User',
    config_mode_guest: 'Guest',
    config_balance: 'Balance: {value}',
    config_guest_tip: 'Guest sessions use a manual 即刻 API key. Register or sign in to bind a per-user key automatically.',
    config_sign_in: 'Sign In',
    config_register: 'Register',
    config_title: 'Runtime Binding',
    config_session_user: '即刻 Account Session',
    config_session_guest: 'Guest Session',
    config_user_desc: 'This config is attached to the signed-in 即刻 user. The personal API key is selected automatically, and you can override it with a shared or welfare key when needed.',
    config_guest_desc: 'Guest mode keeps data isolated by guest cookie. This mode uses a manually saved 即刻 API key, and the backend routes requests to the internal image service.',
	    config_cases: 'Public Case Library',
	    config_cases_summary: '{total} public cases · last {time}',
	    config_cases_engagement: '{likes} likes · {comments} comments',
    config_user_name: 'User Name',
    config_model: 'Model',
    config_size: 'Size',
    config_quality: 'Quality',
    config_api_key: '即刻 Key',
    config_saved_key: 'Saved key: {value}',
    config_key_managed: 'managed',
    config_key_override: 'manual override',
    config_key_manual: 'manual',
    config_restore_key: 'Restore managed key',
    config_test: 'Test Link',
    config_save: 'Save Config',
    config_ledger: 'Consumption Matrix',
    config_ledger_empty: 'No local ledger',
    config_view_ledger: 'View Full Ledger',
    config_status_saved: 'Config saved',
    config_status_connected: 'Connected: {value}',
    config_status_restored: 'Restored managed key',
    config_status_site_saved: 'Site settings saved',
    config_site_title: 'Interface & Announcement',
    config_site_desc: 'Language selection is stored in the current browser. When an admin saves, it also becomes the site default along with the announcement.',
    login_access: 'Access',
    login_title: 'Sign In',
    login_title_2fa: 'Two-Factor Check',
    login_desc: 'Use your 即刻 account. This site keeps its own session cookie and binds your personal API key automatically.',
    login_desc_2fa: 'Enter the 6-digit code for {value}.',
    login_email: 'Email',
    login_password: 'Password',
    login_totp: 'TOTP Code',
    login_submit: 'Sign In',
    login_submit_2fa: 'Verify 2FA',
    login_new: 'New account?',
    register_access: 'Enrollment',
    register_title: 'Create Account',
    register_desc: 'Registration happens from this image site, but the account source is your deployed 即刻 instance.',
    register_disabled: 'Registration is disabled on the connected 即刻 service.',
    register_email: 'Email',
    register_password: 'Password',
    register_verify_code: 'Verify Code',
    register_send_code: 'Send Code',
    register_promo: 'Promo Code',
    register_invitation: 'Invitation Code',
    register_submit: 'Register',
    register_exists: 'Already registered?',
    lang_label: 'Language',
    lang_zh: '中文',
    lang_en: 'English',
    site_announcement: 'Announcement',
    site_announcement_enabled: 'Enable popup announcement',
    site_announcement_title: 'Announcement title',
    site_announcement_body: 'Announcement body',
    site_upstream: 'Upstream Service',
    site_upstream_hint: 'Leave blank to use environment variables. After saving, generation, auth, balance, and usage logs use the new upstream.',
    site_provider_base_url: 'OpenAI-compatible base URL',
    site_auth_base_url: 'Auth management base URL',
    site_upstream_effective: 'Active: {value}',
    site_announcement_save: 'Save Announcement',
    site_settings_save: 'Save Site Settings',
    site_admin_only: 'Only admins can edit site settings.',
    announcement_empty: 'No announcement available.',
    modal_close: 'Close',
    modal_preview: 'Image Preview',
    modal_open_image: 'Open Original',
    tasks_title: 'Task Center',
    tasks_subtitle: 'Submitted generate and edit jobs continue here in the background.',
    tasks_empty: 'No tasks yet.',
    tasks_open_history: 'Open History',
    tasks_active: '{value} active',
    tasks_idle: 'Idle',
    tasks_filter_all: 'All',
    tasks_filter_active: 'Active',
    tasks_filter_succeeded: 'Done',
    tasks_filter_failed: 'Failed',
    tasks_status_queued: 'Queued',
    tasks_status_running: 'Running',
    tasks_status_succeeded: 'Done',
    tasks_status_failed: 'Failed',
    tasks_toast_succeeded: 'Task Complete',
    tasks_toast_failed: 'Task Failed',
  },
} as const;

const SiteContext = createContext<SiteContextValue | null>(null);

export function SiteProvider({ children }: { children: ReactNode }) {
  const { viewer } = useAuth();
  const [siteSettings, setSiteSettings] = useState<SiteSettings | null>(null);
  const [locale, setLocaleState] = useState<Locale>('zh-CN');
  const [announcementOpen, setAnnouncementOpen] = useState(false);

  async function refreshSiteSettings() {
    try {
      const next = await getSiteSettings();
      setSiteSettings(next);
      const storedLocale = window.localStorage.getItem(LOCALE_STORAGE_KEY) as Locale | null;
      if (storedLocale === 'zh-CN' || storedLocale === 'en-US') {
        setLocaleState(storedLocale);
      } else if (next.default_locale === 'en-US' || next.default_locale === 'zh-CN') {
        setLocaleState(next.default_locale);
      } else {
        setLocaleState('zh-CN');
      }
    } catch {
      setSiteSettings(null);
      setLocaleState('zh-CN');
    }
  }

  useEffect(() => {
    refreshSiteSettings().catch(() => undefined);
  }, [viewer?.owner_id]);

  useEffect(() => {
    if (!siteSettings?.announcement.enabled || !siteSettings.announcement.updated_at) {
      return;
    }
    const seenAt = window.localStorage.getItem(ANNOUNCEMENT_SEEN_KEY);
    if (seenAt !== siteSettings.announcement.updated_at) {
      setAnnouncementOpen(true);
    }
  }, [siteSettings?.announcement.enabled, siteSettings?.announcement.updated_at]);

  function setLocale(nextLocale: Locale) {
    setLocaleState(nextLocale);
    window.localStorage.setItem(LOCALE_STORAGE_KEY, nextLocale);
  }

  function openAnnouncement() {
    setAnnouncementOpen(true);
  }

  function closeAnnouncement() {
    setAnnouncementOpen(false);
    const updatedAt = siteSettings?.announcement.updated_at;
    if (updatedAt) {
      window.localStorage.setItem(ANNOUNCEMENT_SEEN_KEY, updatedAt);
    }
  }

  const value = useMemo<SiteContextValue>(() => ({
    locale,
    setLocale,
    t: (key, vars) => {
      const template = translations[locale][key] || translations['zh-CN'][key] || key;
      if (!vars) return template;
      return Object.entries(vars).reduce((result, [name, value]) => result.replace(`{${name}}`, String(value)), template);
    },
    siteSettings,
    refreshSiteSettings,
    announcementOpen,
    openAnnouncement,
    closeAnnouncement,
  }), [locale, siteSettings, announcementOpen]);

  return <SiteContext.Provider value={value}>{children}</SiteContext.Provider>;
}

export function useSite() {
  const context = useContext(SiteContext);
  if (!context) {
    throw new Error('useSite must be used inside SiteProvider');
  }
  return context;
}
